# Generated by Django 5.1.2 on 2024-10-18 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='available',
            field=models.BooleanField(default=False),
        ),
    ]
