# Generated by Django 5.1.2 on 2024-10-23 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_producthistory_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producthistory',
            name='product_id',
            field=models.UUIDField(),
        ),
    ]
