# Generated by Django 5.1.2 on 2024-10-23 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_producthistory_product_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductHistory',
        ),
    ]
