# Generated by Django 5.1.1 on 2024-10-10 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_delete_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='email',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='password',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='username',
        ),
    ]
