# Generated by Django 5.1.1 on 2024-10-11 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_employee_email_remove_employee_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmanager',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('funcionario', 'employee')], max_length=100),
        ),
    ]
