# Generated by Django 5.1.1 on 2024-10-11 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_stockmanager_price_alter_employee_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('employee', 'employee')], max_length=100),
        ),
    ]
