# Generated by Django 5.1.1 on 2024-10-11 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_responsible_user_id_stockmanager_responsible_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockmanager',
            options={},
        ),
        migrations.AlterField(
            model_name='stockmanager',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product'),
        ),
    ]
