# Generated by Django 5.1.2 on 2024-10-30 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
