# Generated by Django 5.1.2 on 2025-01-11 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('people', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='actionhistory',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.employee'),
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.cart'),
        ),
        migrations.AddField(
            model_name='notification',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='people.employee'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.product'),
        ),
        migrations.AddField(
            model_name='producthistory',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.product'),
        ),
        migrations.AddField(
            model_name='sale',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.employee'),
        ),
        migrations.AddField(
            model_name='sale',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.product'),
        ),
        migrations.AddField(
            model_name='actionhistory',
            name='sale',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.sale'),
        ),
        migrations.AddField(
            model_name='salehistory',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.employee'),
        ),
        migrations.AddField(
            model_name='salehistory',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.product'),
        ),
        migrations.AddField(
            model_name='salehistory',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history', to='orders.sale'),
        ),
        migrations.AddField(
            model_name='stock',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.product'),
        ),
        migrations.AddField(
            model_name='stock',
            name='responsible_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.employee'),
        ),
        migrations.AddField(
            model_name='stock',
            name='stock_reference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.stockreference'),
        ),
        migrations.AddField(
            model_name='salehistory',
            name='stock_reference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.stockreference'),
        ),
        migrations.AddField(
            model_name='sale',
            name='stock_reference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.stockreference'),
        ),
        migrations.AddField(
            model_name='producthistory',
            name='stock_reference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.stockreference'),
        ),
        migrations.AddField(
            model_name='notification',
            name='stock_reference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.stockreference'),
        ),
    ]
