# Generated by Django 5.1.2 on 2024-12-07 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockreference',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
