# Generated by Django 5.1.2 on 2024-10-27 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_notification_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='acquisition_value',
        ),
    ]
