# Generated by Django 5.1.2 on 2024-10-30 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_sale_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
