# Generated by Django 5.1.2 on 2024-12-07 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_stockreference_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='stock',
        ),
        migrations.AddField(
            model_name='stock',
            name='stock_reference',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='orders.stockreference'),
            preserve_default=False,
        ),
    ]
