# Generated by Django 5.1.2 on 2024-10-24 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_producthistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producthistory',
            old_name='product_id',
            new_name='product',
        ),
    ]
