# Generated by Django 5.1.2 on 2024-10-30 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_sale_archived_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salehistory',
            old_name='sale_price',
            new_name='sale_total_value',
        ),
    ]
