# Generated by Django 5.1.2 on 2024-12-07 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_stock_stock_stock_stock_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='stock_reference',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='orders.stockreference'),
            preserve_default=False,
        ),
    ]
