# Generated by Django 5.1.2 on 2024-10-27 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_stock_acquisition_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salehistory',
            name='stock_acquisition_value',
        ),
    ]
