# Generated by Django 5.1.2 on 2024-11-07 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_rename_sale_price_salehistory_sale_total_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='producthistory',
            name='product_quantity',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=10),
            preserve_default=False,
        ),
    ]
