# Generated by Django 5.1.2 on 2024-11-08 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_totalproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='totalproduct',
            name='product',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='orders.product'),
            preserve_default=False,
        ),
    ]
