# Generated by Django 5.1.2 on 2025-01-05 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_product_description_alter_product_name'),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='stock_reference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_reference', to='orders.stockreference'),
        ),
    ]
